import { BorderProps } from './interfaces';
import styled from 'styled-components';

export const BorderStyle = styled.div<BorderProps>`
  border: none;
  ${({ b_none }) => b_none && 'border: none;'}
  ${({ b_solid }) => b_solid && 'border-style: solid;'}
  ${({ b_dashed }) => b_dashed && 'border-style: dashed;'}
  ${({ b_dotted }) => b_dotted && 'border-style: dotted;'}
  ${({ b_double }) => b_double && 'border-style: double;'}
  ${({ b_circular }) => b_circular && 'border-radius: 9999px;'}
  ${({ b_rounded }) => b_rounded && 'border-radius: 2rem;'}
  ${({ b_edge }) => b_edge && 'border-radius: .5rem;'}
  ${({ b_thick }) => b_thick && 'border-width: .5rem;'}
  ${({ b_thin }) => b_thin && 'border-width: .05rem;'}
  ${({ b_black }) => b_black && 'border-color: #000;'}
  ${({ b_white }) => b_white && 'border-color: #fff;'}
  ${({ b_grey }) => b_grey && 'border-color: #cbd5e0;'}
  ${({ bx_none }) => bx_none && 'border-right: none;border-left:none;'}
  ${({ bx_solid }) => bx_solid && 'border-right-style: solid;border-left-style: solid;'}
  ${({ bx_dashed }) => bx_dashed && 'border-right-style: dashed;border-left-style: dashed;'}
  ${({ bx_dotted }) => bx_dotted && 'border-right-style: dotted;border-left-style: dotted;'}
  ${({ bx_double }) => bx_double && 'border-right-style: double;border-left-style: double;'}
  ${({ bx_thick }) => bx_thick && 'border-right-width: .5rem;order-left-width: .5rem;'}
  ${({ bx_thin }) => bx_thin && 'border-right-width: .05rem;order-left-width: .05rem;'}
  ${({ bx_black }) => bx_black && 'border-right-color: #000;border-left-color: #000;'}
  ${({ bx_white }) => bx_white && 'border-right-color: #fff;border-left-color: #fff;'}
  ${({ bx_grey }) => bx_grey && 'border-right-color: #cbd5e0;border-left-color: #cbd5e0;'}
  ${({ by_none }) => by_none && 'border-top: none;border-bottom:none;'}
  ${({ by_solid }) => by_solid && 'border-top-style: solid;border-bottom-style: solid;'}
  ${({ by_dashed }) => by_dashed && 'border-top-style: dashed;border-bottom-style: dashed;'}
  ${({ by_dotted }) => by_dotted && 'border-top-style: dotted;border-bottom-style: dotted;'}
  ${({ by_double }) => by_double && 'border-top-style: double;border-bottom-style: double;'}
  ${({ by_thick }) => by_thick && 'border-top-width: .5rem;order-bottom-width: .5rem;'}
  ${({ by_thin }) => by_thin && 'border-top-width: .05rem;order-bottom-width: .05rem;'}
  ${({ by_black }) => by_black && 'border-top-color: #000;border-bottom-color: #000;'}
  ${({ by_white }) => by_white && 'border-top-color: #fff;border-bottom-color: #fff;'}
  ${({ by_grey }) => by_grey && 'border-top-color: #cbd5e0;border-bottom-color: #cbd5e0;'}
  ${({ bt_none }) => bt_none && 'border-top: none;'}
  ${({ bt_solid }) => bt_solid && 'border-top-style: solid;'}
  ${({ bt_dashed }) => bt_dashed && 'border-top-style: dashed;'}
  ${({ bt_dotted }) => bt_dotted && 'border-top-style: dotted;'}
  ${({ bt_double }) => bt_double && 'border-top-style: double;'}
  ${({ bt_circular }) => bt_circular && 'border-top-right-radius: 9999px;border-top-left-radius: 9999px;'}
  ${({ bt_rounded }) => bt_rounded && 'border-top-right-radius: 2rem;border-top-left-radius: 2rem;'}
  ${({ bt_edge }) => bt_edge && 'border-top-right-radius: .5rem;border-top-left-radius: .5rem;'}
  ${({ bt_thick }) => bt_thick && 'border-top-width: .5rem;'}
  ${({ bt_thin }) => bt_thin && 'border-top-width: .05rem;'}
  ${({ bt_black }) => bt_black && 'border-top-color: #000;'}
  ${({ bt_white }) => bt_white && 'border-top-color: #fff;'}
  ${({ bt_grey }) => bt_grey && 'border-top-color: #cbd5e0;'}
  ${({ bb_none }) => bb_none && 'border-bottom:none;'}
  ${({ bb_solid }) => bb_solid && 'border-bottom-style: solid;'}
  ${({ bb_dashed }) => bb_dashed && 'border-bottom-style: dashed;'}
  ${({ bb_dotted }) => bb_dotted && 'border-bottom-style: dotted;'}
  ${({ bb_double }) => bb_double && 'border-bottom-style: double;'}
  ${({ bb_circular }) => bb_circular && 'border-bottom-right-radius: 9999px;border-bottom-left-radius: 9999px;'}
  ${({ bb_rounded }) => bb_rounded && 'border-bottom-right-radius: 2rem;border-bottom-left-radius: 2rem;'}
  ${({ bb_edge }) => bb_edge && 'border-bottom-right-radius: .5rem;border-bottom-left-radius: .5rem;'}
  ${({ bb_thick }) => bb_thick && 'order-bottom-width: .5rem;'}
  ${({ bb_thin }) => bb_thin && 'order-bottom-width: .05rem;'}
  ${({ bb_black }) => bb_black && 'border-bottom-color: #000;'}
  ${({ bb_white }) => bb_white && 'border-bottom-color: #fff;'}
  ${({ bb_grey }) => bb_grey && 'border-bottom-color: #cbd5e0;'}
  ${({ bl_none }) => bl_none && 'border-left:none;'}
  ${({ bl_solid }) => bl_solid && 'border-left-style: solid;'}
  ${({ bl_dashed }) => bl_dashed && 'border-left-style: dashed;'}
  ${({ bl_dotted }) => bl_dotted && 'border-left-style: dotted;'}
  ${({ bl_double }) => bl_double && 'border-left-style: double;'}
  ${({ bl_circular }) => bl_circular && 'border-top-left-radius: 9999px;border-bottom-left-radius: 9999px;'}
  ${({ bl_rounded }) => bl_rounded && 'border-top-left-radius: 2rem;border-bottom-left-radius: 2rem;'}
  ${({ bl_edge }) => bl_edge && 'border-top-left-radius: .5rem;border-bottom-left-radius: .5rem;'}
  ${({ bl_thick }) => bl_thick && 'order-left-width: .5rem;'}
  ${({ bl_thin }) => bl_thin && 'order-left-width: .05rem;'}
  ${({ bl_black }) => bl_black && 'border-left-color: #000;'}
  ${({ bl_white }) => bl_white && 'border-left-color: #fff;'}
  ${({ bl_grey }) => bl_grey && 'border-left-color: #cbd5e0;'}
  ${({ br_none }) => br_none && 'border-right:none;'}
  ${({ br_solid }) => br_solid && 'border-right-style: solid;'}
  ${({ br_dashed }) => br_dashed && 'border-right-style: dashed;'}
  ${({ br_dotted }) => br_dotted && 'border-right-style: dotted;'}
  ${({ br_double }) => br_double && 'border-right-style: double;'}
  ${({ br_circular }) => br_circular && 'border-top-right-radius: 9999px;border-bottom-right-radius: 9999px;'}
  ${({ br_rounded }) => br_rounded && 'border-top-right-radius: 2rem;border-bottom-right-radius: 2rem;'}
  ${({ br_edge }) => br_edge && 'border-top-right-radius: .5rem;border-bottom-right-radius: .5rem;'}
  ${({ br_thick }) => br_thick && 'border-right-width: .5rem;'}
  ${({ br_thin }) => br_thin && 'border-right-width: .05rem;'}
  ${({ br_black }) => br_black && 'border-right-color: #000;'}
  ${({ br_white }) => br_white && 'border-right-color: #fff;'}
  ${({ br_grey }) => br_grey && 'border-right-color: #cbd5e0;'}
  ${({ btr_circular }) => btr_circular && 'border-top-right-radius: 9999px;'}
  ${({ btr_rounded }) => btr_rounded && 'border-top-right-radius: 2rem;'}
  ${({ btr_edge }) => btr_edge && 'border-top-right-radius: .5rem;'}
  ${({ btl_circular }) => btl_circular && 'border-top-left-radius: 9999px;'}
  ${({ btl_rounded }) => btl_rounded && 'border-top-left-radius: 2rem;'}
  ${({ btl_edge }) => btl_edge && 'border-top-left-radius: .5rem;'}
  ${({ bbr_circular }) => bbr_circular && 'border-bottom-right-radius: 9999px;'}
  ${({ bbr_rounded }) => bbr_rounded && 'border-bottom-right-radius: 2rem;'}
  ${({ bbr_edge }) => bbr_edge && 'border-bottom-right-radius: .5rem;'}
  ${({ bbl_circular }) => bbl_circular && 'border-bottom-left-radius: 9999px;'}
  ${({ bbl_rounded }) => bbl_rounded && 'border-bottom-left-radius: 2rem;'}
  ${({ bbl_edge }) => bbl_edge && 'border-bottom-left-radius: .5rem;'}
`;