import TransformProps from './interfaces';
import { indexerCss } from '../../lib/indexer';

const transformCss = indexerCss<TransformProps>([
  [/^(sl_)(\d+)/, (value) => `transform: scale(${value}rem,${value}rem);`],
  [/^(slx_)(\d+)/, (value) => `transform: scaleX(${value}rem);`],
  [/^(sly_)(\d+)/, (value) => `transform: scaleY(${value}rem);`],
  [/^(rt_)(\d+)/, (value) => `transform: rotate(${value}deg);`],
  [/^(tl_)(\d+)/, (value) => `transform: translate(${value}rem,${value}rem);`],
  [/^(tlx_)(\d+)/, (value) => `transform: translateX(${value}rem);`],
  [/^(tly_)(\d+)/, (value) => `transform: translateY(${value}rem);`],
  [/^(sk_)(\d+)/, (value) => `transform: skew(${value}deg,${value}deg);`],
  [/^(skx_)(\d+)/, (value) => `transform: skewX(${value}deg);`],
  [/^(sky_)(\d+)/, (value) => `transform: skewY(${value}deg);`],
  [/^(sk_neg_)(\d+)/, (value) => `transform: skew(-${value}deg,-${value}deg);`],
  [/^(skx_neg_)(\d+)/, (value) => `transform: skewX(-${value}deg);`],
  [/^(sky_neg_)(\d+)/, (value) => `transform: skewY(-${value}deg);`],
  [/^(sl_neg_)(\d+)/, (value) => `transform: scale(-${value}rem,-${value}rem);`],
  [/^(slx_neg_)(\d+)/, (value) => `transform: scaleX(-${value}rem);`],
  [/^(sly_neg_)(\d+)/, (value) => `transform: scaleY(-${value}rem);`],
  [/^(rt_neg_)(\d+)/, (value) => `transform: rotate(-${value}deg);`],
  [/^(tl_neg_)(\d+)/, (value) => `transform: translate(-${value}rem,-${value}rem);`],
  [/^(tlx_neg_)(\d+)/, (value) => `transform: translateX(-${value}rem);`],
  [/^(tly_neg_)(\d+)/, (value) => `transform: translateY(-${value}rem);`],
  ['tl_full', () => 'transform: translate(100%, 100%);'],
  ['tl_half', () => 'transform: translate(50%, 50%);'],
  ['tl_full_neg', () => 'transform: translate(-100%, -100%);'],
  ['tl_half_neg', () => 'transform: translate(-50%, -50%);'],
  ['tlx_full', () => 'transform: translateX(100%);'],
  ['tlx_half', () => 'transform: translateX(50%);'],
  ['tlx_full_neg', () => 'transform: translateX(-100%);'],
  ['tlx_half_neg', () => 'transform: translateX(-50%);'],
  ['tly_full', () => 'transform: translateY(100%);'],
  ['tly_half', () => 'transform: translateY(50%);'],
  ['tly_full_neg', () => 'transform: translateY(-100%);'],
  ['tly_half_neg', () => 'transform: translateY(-50%);'],
  ['ori_center', () => 'transform-origin: center;'],
  ['ori_top', () => 'transform-origin: top;'],
  ['ori_top_right', () => 'transform-origin: top right;'],
  ['ori_right', () => 'transform-origin: right;'],
  ['ori_bottom_right', () => 'transform-origin: bottom right;'],
  ['ori_bottom', () => 'transform-origin: bottom;'],
  ['ori_bottom_left', () => 'transform-origin: bottom left;'],
  ['ori_left', () => 'transform-origin: left;'],
  ['ori_top_left', () => 'transform-origin: top left;'],
])

export default transformCss;
