env:
  browser: true
  es6: true
extends:
  - "prettier"
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
  - react
  - "@typescript-eslint"
  - "eslint-plugin-import-helpers"
rules:
  "prettier/prettier":
    - warn
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: true
  import-helpers/order-imports:
    - warn
    - newlinesBetween: always
      groups:
      - /react/
      - /boolean/
      - module
      - - parent
        - sibling
        - index
      alphabetize:
        order: asc
        ignoreCase: true
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
overrides:
  - files:
      - "*"
    rules:
      "@typescript-eslint/camelcase": off
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/explicit-module-boundary-types": off
      "@typescript-eslint/no-explicit-any": off
      "react/prop-types": off
      "react/display-name": off
      "noImplicitAny": off
