env:
  browser: true
  es6: true
extends:
  - "prettier"
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
    modules: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
  - react
  - "@typescript-eslint"
  - eslint-plugin-sort-imports-es6-autofix
rules:
  "prettier/prettier":
    - warn
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: true
  sort-imports-es6-autofix/sort-imports-es6:
    - warn
    - ignoreCase: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - single
        - all
        - multiple
        - none
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
overrides:
  - files:
      - "*"
    rules:
      "@typescript-eslint/camelcase": off
      "@typescript-eslint/explicit-function-return-type": off
      "@typescript-eslint/no-explicit-any": off
      "react/prop-types": off
      "react/display-name": off
      "noImplicitAny": off
