env:
  browser: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - eslint-plugin-sort-imports-es6-autofix
rules:
  "@typescript-eslint/explicit-function-return-type":
    - warn
    - allowExpressions: true
  sort-imports-es6-autofix/sort-imports-es6:
    - warn
  indent:
    - warn
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
# overrides:
#   - files:
#       - "*.js"
#       - "*.jsx"
#     rules:
#       "@typescript-eslint/eslint-plugin-tslint": off
