module.exports = {
  rotation: {
    0: { value: '0deg' },
    45: { value: '45deg' },
    90: { value: '90deg' },
    135: { value: '135deg' },
    180: { value: '180deg' },
    225: { value: '225deg' },
    360: { value: '360deg' },
  },
  relative: {
    10: { value: '{absolute.10.value}', attributes: { category: 'aaa' } },
    20: { value: '{absolute.20.value}', attributes: { category: 'aaa' } },
    30: { value: '{absolute.30.value}', attributes: { category: 'aaa' } },
    40: { value: '{absolute.40.value}', attributes: { category: 'aaa' } },
    50: { value: '{absolute.50.value}', attributes: { category: 'aaa' } },
    60: { value: '{absolute.60.value}', attributes: { category: 'aaa' } },
    70: { value: '{absolute.70.value}', attributes: { category: 'aaa' } },
    80: { value: '{absolute.80.value}', attributes: { category: 'aaa' } },
    90: { value: '{absolute.90.value}', attributes: { category: 'aaa' } },
    100: {
      value: '{absolute.100.value}',
      attributes: { category: 'aaa' },
    },
  },
  percentage: {
    10: { value: '{absolute.10.value}%' },
    20: { value: '{absolute.20.value}%' },
    30: { value: '{absolute.30.value}%' },
    40: { value: '{absolute.40.value}%' },
    50: { value: '{absolute.50.value}%' },
    60: { value: '{absolute.60.value}%' },
    70: { value: '{absolute.70.value}%' },
    80: { value: '{absolute.80.value}%' },
    90: { value: '{absolute.90.value}%' },
    100: { value: '{absolute.100.value}%' },
  },
  sizes: {
    percentage: '{percentage}',
    screen: {
      width: {
        10: { value: '{absolute.10.value}vw' },
        20: { value: '{absolute.20.value}vw' },
        30: { value: '{absolute.30.value}vw' },
        40: { value: '{absolute.40.value}vw' },
        50: { value: '{absolute.50.value}vw' },
        60: { value: '{absolute.60.value}vw' },
        70: { value: '{absolute.70.value}vw' },
        80: { value: '{absolute.80.value}vw' },
        90: { value: '{absolute.90.value}vw' },
        100: { value: '{absolute.100.value}vw' },
      },
      height: {
        10: { value: '{absolute.10.value}vh' },
        20: { value: '{absolute.20.value}vh' },
        30: { value: '{absolute.30.value}vh' },
        40: { value: '{absolute.40.value}vh' },
        50: { value: '{absolute.50.value}vh' },
        60: { value: '{absolute.60.value}vh' },
        70: { value: '{absolute.70.value}vh' },
        80: { value: '{absolute.80.value}vh' },
        90: { value: '{absolute.90.value}vh' },
        100: { value: '{absolute.100.value}vh' },
      },
    },
    auto: {
      value: 'auto',
    },
    none: {
      value: '{scaled.none.value}',
      attributes: { category: 'rxm' },
    },
    px: {
      value: '{scaled.px.value}',
      attributes: { category: 'rxm' },
    },
    xs: {
      value: '{scaled.xs.value}',
      attributes: { category: 'rxm' },
    },
    sm: {
      value: '{scaled.sm.value}',
      attributes: { category: 'rxm' },
    },
    md: {
      value: '{scaled.md.value}',
      attributes: { category: 'rxm' },
    },
    lg: {
      value: '{scaled.lg.value}',
      attributes: { category: 'rxm' },
    },
    xl: {
      value: '{scaled.xl.value}',
      attributes: { category: 'rxm' },
    },
    '2xl': {
      value: '{scaled.2xl.value}',
      attributes: { category: 'rxm' },
    },
    '3xl': {
      value: '{scaled.3xl.value}',
      attributes: { category: 'rxm' },
    },
    '4xl': {
      value: '{scaled.4xl.value}',
      attributes: { category: 'rxm' },
    },
    '5xl': {
      value: '{scaled.5xl.value}',
      attributes: { category: 'rxm' },
    },
    '6xl': {
      value: '{scaled.6xl.value}',
      attributes: { category: 'rxm' },
    },
    '7xl': {
      value: '{scaled.7xl.value}',
      attributes: { category: 'rxm' },
    },
    '8xl': {
      value: '{scaled.8xl.value}',
      attributes: { category: 'rxm' },
    },
    '9xl': {
      value: '{scaled.9xl.value}',
      attributes: { category: 'rxm' },
    },
    '10xl': {
      value: '{scaled.10xl.value}',
      attributes: { category: 'rxm' },
    },
    '11xl': {
      value: '{scaled.11xl.value}',
      attributes: { category: 'rxm' },
    },
    '12xl': {
      value: '{scaled.12xl.value}',
      attributes: { category: 'rxm' },
    },
    '13xl': {
      value: '{scaled.13xl.value}',
      attributes: { category: 'rxm' },
    },
    '14xl': {
      value: '{scaled.14xl.value}',
      attributes: { category: 'rxm' },
    },
    '15xl': {
      value: '{scaled.15xl.value}',
      attributes: { category: 'rxm' },
    },
    '16xl': {
      value: '{scaled.16xl.value}',
      attributes: { category: 'rxm' },
    },
  },
  thickness: {
    none: {
      value: '{scaled.none.value}',
      attributes: { category: 'rxm' },
    },
    px: {
      value: '{scaled.px.value}',
      attributes: { category: 'rxm' },
    },
    xs: {
      value: '{scaled.xs.value}',
      attributes: { category: 'rxm' },
    },
    sm: {
      value: '{scaled.sm.value}',
      attributes: { category: 'rxm' },
    },
    md: {
      value: '{scaled.md.value}',
      attributes: { category: 'rxm' },
    },
    lg: {
      value: '{scaled.lg.value}',
      attributes: { category: 'rxm' },
    },
    xl: {
      value: '{scaled.xl.value}',
      attributes: { category: 'rxm' },
    },
  },
  radius: {
    none: {
      value: '{scaled.none.value}',
      attributes: { category: 'rxm' },
    },
    px: {
      value: '{scaled.px.value}',
      attributes: { category: 'rxm' },
    },
    xs: {
      value: '{scaled.xs.value}',
      attributes: { category: 'rxm' },
    },
    sm: {
      value: '{scaled.sm.value}',
      attributes: { category: 'rxm' },
    },
    md: {
      value: '{scaled.md.value}',
      attributes: { category: 'rxm' },
    },
    lg: {
      value: '{scaled.lg.value}',
      attributes: { category: 'rxm' },
    },
    xl: {
      value: '{scaled.xl.value}',
      attributes: { category: 'rxm' },
    },
    circle: {
      value: '{scaled.xl.value}',
      attributes: { category: 'rxm' },
    },
    pill: {
      value: '{scaled.xl.value}',
      attributes: { category: 'rxm' },
    },
  },
  spaces: {
    auto: {
      value: 'auto',
    },
    none: {
      value: '{scaled.none.value}',
      attributes: { category: 'rxm' },
    },
    px: {
      value: '{scaled.px.value}',
      attributes: { category: 'rxm' },
    },
    xs: {
      value: '{scaled.xs.value}',
      attributes: { category: 'rxm' },
    },
    sm: {
      value: '{scaled.sm.value}',
      attributes: { category: 'rxm' },
    },
    md: {
      value: '{scaled.md.value}',
      attributes: { category: 'rxm' },
    },
    lg: {
      value: '{scaled.lg.value}',
      attributes: { category: 'rxm' },
    },
    xl: {
      value: '{scaled.xl.value}',
      attributes: { category: 'rxm' },
    },
  },
  scaled: {
    none: { value: '0' },
    px: { value: '1' },
    xs: { value: '2' },
    sm: { value: '4' },
    md: { value: '6' },
    lg: { value: '8' },
    xl: { value: '12' },
    '2xl': { value: '16' },
    '3xl': { value: '24' },
    '4xl': { value: '32' },
    '5xl': { value: '48' },
    '6xl': { value: '64' },
    '7xl': { value: '96' },
    '8xl': { value: '128' },
    '9xl': { value: '256' },
    '10xl': { value: '192' },
    '11xl': { value: '384' },
    '12xl': { value: '512' },
    '13xl': { value: '768' },
    '14xl': { value: '1024' },
    '15xl': { value: '1536' },
    '16xl': { value: '2048' },
  },
  absolute: {
    1: { value: '1' },
    2: { value: '2' },
    3: { value: '3' },
    4: { value: '4' },
    5: { value: '5' },
    6: { value: '6' },
    7: { value: '7' },
    8: { value: '8' },
    9: { value: '9' },
    10: { value: '10' },
    11: { value: '11' },
    12: { value: '12' },
    13: { value: '13' },
    14: { value: '14' },
    15: { value: '15' },
    16: { value: '16' },
    17: { value: '17' },
    18: { value: '18' },
    19: { value: '19' },
    20: { value: '20' },
    21: { value: '21' },
    22: { value: '22' },
    23: { value: '23' },
    24: { value: '24' },
    25: { value: '25' },
    26: { value: '26' },
    27: { value: '27' },
    28: { value: '28' },
    29: { value: '29' },
    30: { value: '30' },
    31: { value: '31' },
    32: { value: '32' },
    33: { value: '33' },
    34: { value: '34' },
    35: { value: '35' },
    36: { value: '36' },
    37: { value: '37' },
    38: { value: '38' },
    39: { value: '39' },
    40: { value: '40' },
    41: { value: '41' },
    42: { value: '42' },
    43: { value: '43' },
    44: { value: '44' },
    45: { value: '45' },
    46: { value: '46' },
    47: { value: '47' },
    48: { value: '48' },
    49: { value: '49' },
    50: { value: '50' },
    51: { value: '51' },
    52: { value: '52' },
    53: { value: '53' },
    54: { value: '54' },
    55: { value: '55' },
    56: { value: '56' },
    57: { value: '57' },
    58: { value: '58' },
    59: { value: '59' },
    60: { value: '60' },
    61: { value: '61' },
    62: { value: '62' },
    63: { value: '63' },
    64: { value: '64' },
    65: { value: '65' },
    66: { value: '66' },
    67: { value: '67' },
    68: { value: '68' },
    69: { value: '69' },
    70: { value: '70' },
    71: { value: '71' },
    72: { value: '72' },
    73: { value: '73' },
    74: { value: '74' },
    75: { value: '75' },
    76: { value: '76' },
    77: { value: '77' },
    78: { value: '78' },
    79: { value: '79' },
    80: { value: '80' },
    81: { value: '81' },
    82: { value: '82' },
    83: { value: '83' },
    84: { value: '84' },
    85: { value: '85' },
    86: { value: '86' },
    87: { value: '87' },
    88: { value: '88' },
    89: { value: '89' },
    90: { value: '90' },
    91: { value: '91' },
    92: { value: '92' },
    93: { value: '93' },
    94: { value: '94' },
    95: { value: '95' },
    96: { value: '96' },
    97: { value: '97' },
    98: { value: '98' },
    99: { value: '99' },
    100: { value: '100' },
  },
};
