import { selector } from './selectorsHandlers';

export const selectorsDefault = {
  undefined: () => '',
  css: selector.classes(),
  dark: selector.theme(),
  important: selector.important(),
  xs: selector.media('(min-width: 640px)'),
  sm: selector.media('(min-width: 768px)'),
  md: selector.media('(min-width: 1024px)'),
  lg: selector.media('(min-width: 1440px)'),
  xl: selector.media('(min-width: 1920px)'),
  not: selector.pseudo(() => ':not'),
  is: selector.pseudo(() => ':is'),
  focus: selector.pseudo(':focus'),
  within: selector.pseudo(':focus-within'),
  after: selector.pseudo(':after'),
  before: selector.pseudo(':before'),
  active: selector.pseudo(':active'),
  checked: selector.pseudo(':checked'),
  disabled: selector.pseudo(':disabled'),
  hover: selector.pseudo(':hover'),
  visited: selector.pseudo(':visited'),
  child: selector.pseudo('>*'),
  last: selector.pseudo('>:last-child'),
  first: selector.pseudo('>:first-child'),
  adjacent: selector.pseudo('~*'),
  sibling: selector.pseudo('+*'),
  odd: selector.pseudo(':nth-child(odd)'),
  even: selector.pseudo(':nth-child(even)'),
  kf: selector.keyframe({
    from: '0%',
    quarter: '25%',
    third: '33%',
    half: '50%',
    x2third: '66%',
    x3quarter: '75%',
    to: '100%',
  }),
};
