import {
  KeyinTypeOrString,
} from '../../helpers/interfaces';

type Options =
  | 'fb_HEX'
  | 'fc_HEX'
  | 'fs_NUMBER'
  | 'ff_sans'
  | 'ff_serif'
  | 'ff_mono'
  | 'f_italic'
  | 'fsl_none'
  | 'fsl_text'
  | 'fsl_all'
  | 'fsl_auto'
  | 'fw_lightest'
  | 'fw_lighter'
  | 'fw_light'
  | 'fw_normal'
  | 'fw_medium'
  | 'fw_semibold'
  | 'fw_bold'
  | 'fw_bolder'
  | 'fw_black'
  | 'ls_tighter'
  | 'ls_tight'
  | 'ls_normal'
  | 'ls_wide'
  | 'ls_wider'
  | 'ls_widest'
  | 'lh_none'
  | 'lh_tight'
  | 'lh_snug'
  | 'lh_normal'
  | 'lh_relaxed'
  | 'lh_loose'
  | 'li_none'
  | 'li_disc'
  | 'li_decimal'
  | 'li_inside'
  | 'li_outside'
  | 'f_left'
  | 'f_center'
  | 'f_right'
  | 'f_justify'
  | 'f_underline'
  | 'f_line_through'
  | 'f_no_underline'
  | 'ft_uppercase'
  | 'ft_lowercase'
  | 'ft_capitalize'
  | 'ft_normal'
  | 'f_wrap_space'
  | 'f_wrap_word'
  | 'f_wrap_letter'
  | 'f_no_wrap'
  | 'f_no_wrap'
  | 'f_truncate';

type Props = KeyinTypeOrString<Options>;

export default Props;
