import { KeyInType } from '../../lib/interfaces';

type Options =
  | 'fb_HEX'
  | 'fc_HEX'
  | 'fs_NUMBER'
  | 'fsl_none'
  | 'fsl_text'
  | 'fsl_all'
  | 'fsl_auto'
  | 'ls_NUMBER'
  | 'ls_neg_NUMBER'
  | 'lh_NUMBER'
  | 'fa_left'
  | 'fa_center'
  | 'fa_right'
  | 'fa_justify'
  | 'ft_uppercase'
  | 'ft_lowercase'
  | 'ft_normal'
  | 'ft_capitalize'
  | 'ff_CUSTOM_FONT'
  | 'ff_sans'
  | 'ff_serif'
  | 'ff_mono'
  | 'f_italic'
  | 'fw_lightest'
  | 'fw_lighter'
  | 'fw_light'
  | 'fw_normal'
  | 'fw_medium'
  | 'fw_semibold'
  | 'fw_bold'
  | 'fw_bolder'
  | 'fw_black'
  | 'li_none'
  | 'li_disc'
  | 'li_decimal'
  | 'li_inside'
  | 'li_outside'
  | 'f_underline'
  | 'f_line_through'
  | 'f_no_underline'
  | 'f_wrap_space'
  | 'f_wrap_word'
  | 'f_wrap_letter'
  | 'f_no_wrap'
  | 'f_truncate';

type Props = KeyInType<Options>;

export default Props;
