import { flex } from './flex';

test('flex', () => {
  expect(Object.keys(flex).map((key) => flex[key]())).toMatchInlineSnapshot(`
    Array [
      "gap:auto;",
      "gap:0rem;",
      "gap:0.0625rem;",
      "gap:0.125rem;",
      "gap:0.25rem;",
      "gap:0.375rem;",
      "gap:0.5rem;",
      "gap:0.75rem;",
      "gap:1rem;",
      "gap:1.5rem;",
      "gap:2rem;",
      "gap:3rem;",
      "gap:10%;",
      "gap:20%;",
      "gap:30%;",
      "gap:40%;",
      "gap:50%;",
      "gap:60%;",
      "gap:70%;",
      "gap:80%;",
      "gap:90%;",
      "gap:100%;",
      "display:flex;",
      "flex-wrap:wrap;",
      "flex-wrap:nowrap;",
      "flex-wrap:wrap-reverse;",
      "flex-grow:1;",
      "flex-direction:column;",
      "flex-direction:row;",
      "flex-direction:row-reverse;",
      "flex-direction:column-reverse;",
      "justify-content:space-between;",
      "justify-content:space-around;",
      "justify-content:space-evenly;",
      "justify-content:center;",
      "align-items:center;",
      "justify-content:stretch;",
      "align-items:stretch;",
      "justify-content:flex-start;",
      "align-items:flex-start;",
      "justify-content:flex-end;",
      "align-items:flex-end;",
    ]
  `);
});
