import { grid } from './grid';

test('grid', () => {
  expect(Object.keys(grid).map((key) => grid[key]())).toMatchInlineSnapshot(`
    Array [
      "display:grid;",
      "grid-template-areas:undefined;",
      "grid-column:span 1 / span 1;",
      "grid-column:span 2 / span 2;",
      "grid-column:span 3 / span 3;",
      "grid-column:span 4 / span 4;",
      "grid-column:span 5 / span 5;",
      "grid-column:span 6 / span 6;",
      "grid-column:span 7 / span 7;",
      "grid-column:span 8 / span 8;",
      "grid-column:span 9 / span 9;",
      "grid-column:span 10 / span 10;",
      "grid-column:span 11 / span 11;",
      "grid-column:span 12 / span 12;",
      "grid-column:span 13 / span 13;",
      "grid-column:span 14 / span 14;",
      "grid-column:span 15 / span 15;",
      "grid-column:span 16 / span 16;",
      "grid-column:span 17 / span 17;",
      "grid-column:span 18 / span 18;",
      "grid-column:span 19 / span 19;",
      "grid-column:span 20 / span 20;",
      "grid-column:span 21 / span 21;",
      "grid-column:span 22 / span 22;",
      "grid-column:span 23 / span 23;",
      "grid-column:span 24 / span 24;",
      "grid-column:span 25 / span 25;",
      "grid-column:span 26 / span 26;",
      "grid-column:span 27 / span 27;",
      "grid-column:span 28 / span 28;",
      "grid-column:span 29 / span 29;",
      "grid-column:span 30 / span 30;",
      "grid-column:span 31 / span 31;",
      "grid-column:span 32 / span 32;",
      "grid-column:span 33 / span 33;",
      "grid-column:span 34 / span 34;",
      "grid-column:span 35 / span 35;",
      "grid-column:span 36 / span 36;",
      "grid-column:span 37 / span 37;",
      "grid-column:span 38 / span 38;",
      "grid-column:span 39 / span 39;",
      "grid-column:span 40 / span 40;",
      "grid-column:span 41 / span 41;",
      "grid-column:span 42 / span 42;",
      "grid-column:span 43 / span 43;",
      "grid-column:span 44 / span 44;",
      "grid-column:span 45 / span 45;",
      "grid-column:span 46 / span 46;",
      "grid-column:span 47 / span 47;",
      "grid-column:span 48 / span 48;",
      "grid-column:span 49 / span 49;",
      "grid-column:span 50 / span 50;",
      "grid-column:span 51 / span 51;",
      "grid-column:span 52 / span 52;",
      "grid-column:span 53 / span 53;",
      "grid-column:span 54 / span 54;",
      "grid-column:span 55 / span 55;",
      "grid-column:span 56 / span 56;",
      "grid-column:span 57 / span 57;",
      "grid-column:span 58 / span 58;",
      "grid-column:span 59 / span 59;",
      "grid-column:span 60 / span 60;",
      "grid-column:span 61 / span 61;",
      "grid-column:span 62 / span 62;",
      "grid-column:span 63 / span 63;",
      "grid-column:span 64 / span 64;",
      "grid-column:span 65 / span 65;",
      "grid-column:span 66 / span 66;",
      "grid-column:span 67 / span 67;",
      "grid-column:span 68 / span 68;",
      "grid-column:span 69 / span 69;",
      "grid-column:span 70 / span 70;",
      "grid-column:span 71 / span 71;",
      "grid-column:span 72 / span 72;",
      "grid-column:span 73 / span 73;",
      "grid-column:span 74 / span 74;",
      "grid-column:span 75 / span 75;",
      "grid-column:span 76 / span 76;",
      "grid-column:span 77 / span 77;",
      "grid-column:span 78 / span 78;",
      "grid-column:span 79 / span 79;",
      "grid-column:span 80 / span 80;",
      "grid-column:span 81 / span 81;",
      "grid-column:span 82 / span 82;",
      "grid-column:span 83 / span 83;",
      "grid-column:span 84 / span 84;",
      "grid-column:span 85 / span 85;",
      "grid-column:span 86 / span 86;",
      "grid-column:span 87 / span 87;",
      "grid-column:span 88 / span 88;",
      "grid-column:span 89 / span 89;",
      "grid-column:span 90 / span 90;",
      "grid-column:span 91 / span 91;",
      "grid-column:span 92 / span 92;",
      "grid-column:span 93 / span 93;",
      "grid-column:span 94 / span 94;",
      "grid-column:span 95 / span 95;",
      "grid-column:span 96 / span 96;",
      "grid-column:span 97 / span 97;",
      "grid-column:span 98 / span 98;",
      "grid-column:span 99 / span 99;",
      "grid-column:span 100 / span 100;",
      "grid-row:span 1 / span 1;",
      "grid-row:span 2 / span 2;",
      "grid-row:span 3 / span 3;",
      "grid-row:span 4 / span 4;",
      "grid-row:span 5 / span 5;",
      "grid-row:span 6 / span 6;",
      "grid-row:span 7 / span 7;",
      "grid-row:span 8 / span 8;",
      "grid-row:span 9 / span 9;",
      "grid-row:span 10 / span 10;",
      "grid-row:span 11 / span 11;",
      "grid-row:span 12 / span 12;",
      "grid-row:span 13 / span 13;",
      "grid-row:span 14 / span 14;",
      "grid-row:span 15 / span 15;",
      "grid-row:span 16 / span 16;",
      "grid-row:span 17 / span 17;",
      "grid-row:span 18 / span 18;",
      "grid-row:span 19 / span 19;",
      "grid-row:span 20 / span 20;",
      "grid-row:span 21 / span 21;",
      "grid-row:span 22 / span 22;",
      "grid-row:span 23 / span 23;",
      "grid-row:span 24 / span 24;",
      "grid-row:span 25 / span 25;",
      "grid-row:span 26 / span 26;",
      "grid-row:span 27 / span 27;",
      "grid-row:span 28 / span 28;",
      "grid-row:span 29 / span 29;",
      "grid-row:span 30 / span 30;",
      "grid-row:span 31 / span 31;",
      "grid-row:span 32 / span 32;",
      "grid-row:span 33 / span 33;",
      "grid-row:span 34 / span 34;",
      "grid-row:span 35 / span 35;",
      "grid-row:span 36 / span 36;",
      "grid-row:span 37 / span 37;",
      "grid-row:span 38 / span 38;",
      "grid-row:span 39 / span 39;",
      "grid-row:span 40 / span 40;",
      "grid-row:span 41 / span 41;",
      "grid-row:span 42 / span 42;",
      "grid-row:span 43 / span 43;",
      "grid-row:span 44 / span 44;",
      "grid-row:span 45 / span 45;",
      "grid-row:span 46 / span 46;",
      "grid-row:span 47 / span 47;",
      "grid-row:span 48 / span 48;",
      "grid-row:span 49 / span 49;",
      "grid-row:span 50 / span 50;",
      "grid-row:span 51 / span 51;",
      "grid-row:span 52 / span 52;",
      "grid-row:span 53 / span 53;",
      "grid-row:span 54 / span 54;",
      "grid-row:span 55 / span 55;",
      "grid-row:span 56 / span 56;",
      "grid-row:span 57 / span 57;",
      "grid-row:span 58 / span 58;",
      "grid-row:span 59 / span 59;",
      "grid-row:span 60 / span 60;",
      "grid-row:span 61 / span 61;",
      "grid-row:span 62 / span 62;",
      "grid-row:span 63 / span 63;",
      "grid-row:span 64 / span 64;",
      "grid-row:span 65 / span 65;",
      "grid-row:span 66 / span 66;",
      "grid-row:span 67 / span 67;",
      "grid-row:span 68 / span 68;",
      "grid-row:span 69 / span 69;",
      "grid-row:span 70 / span 70;",
      "grid-row:span 71 / span 71;",
      "grid-row:span 72 / span 72;",
      "grid-row:span 73 / span 73;",
      "grid-row:span 74 / span 74;",
      "grid-row:span 75 / span 75;",
      "grid-row:span 76 / span 76;",
      "grid-row:span 77 / span 77;",
      "grid-row:span 78 / span 78;",
      "grid-row:span 79 / span 79;",
      "grid-row:span 80 / span 80;",
      "grid-row:span 81 / span 81;",
      "grid-row:span 82 / span 82;",
      "grid-row:span 83 / span 83;",
      "grid-row:span 84 / span 84;",
      "grid-row:span 85 / span 85;",
      "grid-row:span 86 / span 86;",
      "grid-row:span 87 / span 87;",
      "grid-row:span 88 / span 88;",
      "grid-row:span 89 / span 89;",
      "grid-row:span 90 / span 90;",
      "grid-row:span 91 / span 91;",
      "grid-row:span 92 / span 92;",
      "grid-row:span 93 / span 93;",
      "grid-row:span 94 / span 94;",
      "grid-row:span 95 / span 95;",
      "grid-row:span 96 / span 96;",
      "grid-row:span 97 / span 97;",
      "grid-row:span 98 / span 98;",
      "grid-row:span 99 / span 99;",
      "grid-row:span 100 / span 100;",
      "grid-column-start:1;",
      "grid-column-start:2;",
      "grid-column-start:3;",
      "grid-column-start:4;",
      "grid-column-start:5;",
      "grid-column-start:6;",
      "grid-column-start:7;",
      "grid-column-start:8;",
      "grid-column-start:9;",
      "grid-column-start:10;",
      "grid-column-start:11;",
      "grid-column-start:12;",
      "grid-column-start:13;",
      "grid-column-start:14;",
      "grid-column-start:15;",
      "grid-column-start:16;",
      "grid-column-start:17;",
      "grid-column-start:18;",
      "grid-column-start:19;",
      "grid-column-start:20;",
      "grid-column-start:21;",
      "grid-column-start:22;",
      "grid-column-start:23;",
      "grid-column-start:24;",
      "grid-column-start:25;",
      "grid-column-start:26;",
      "grid-column-start:27;",
      "grid-column-start:28;",
      "grid-column-start:29;",
      "grid-column-start:30;",
      "grid-column-start:31;",
      "grid-column-start:32;",
      "grid-column-start:33;",
      "grid-column-start:34;",
      "grid-column-start:35;",
      "grid-column-start:36;",
      "grid-column-start:37;",
      "grid-column-start:38;",
      "grid-column-start:39;",
      "grid-column-start:40;",
      "grid-column-start:41;",
      "grid-column-start:42;",
      "grid-column-start:43;",
      "grid-column-start:44;",
      "grid-column-start:45;",
      "grid-column-start:46;",
      "grid-column-start:47;",
      "grid-column-start:48;",
      "grid-column-start:49;",
      "grid-column-start:50;",
      "grid-column-start:51;",
      "grid-column-start:52;",
      "grid-column-start:53;",
      "grid-column-start:54;",
      "grid-column-start:55;",
      "grid-column-start:56;",
      "grid-column-start:57;",
      "grid-column-start:58;",
      "grid-column-start:59;",
      "grid-column-start:60;",
      "grid-column-start:61;",
      "grid-column-start:62;",
      "grid-column-start:63;",
      "grid-column-start:64;",
      "grid-column-start:65;",
      "grid-column-start:66;",
      "grid-column-start:67;",
      "grid-column-start:68;",
      "grid-column-start:69;",
      "grid-column-start:70;",
      "grid-column-start:71;",
      "grid-column-start:72;",
      "grid-column-start:73;",
      "grid-column-start:74;",
      "grid-column-start:75;",
      "grid-column-start:76;",
      "grid-column-start:77;",
      "grid-column-start:78;",
      "grid-column-start:79;",
      "grid-column-start:80;",
      "grid-column-start:81;",
      "grid-column-start:82;",
      "grid-column-start:83;",
      "grid-column-start:84;",
      "grid-column-start:85;",
      "grid-column-start:86;",
      "grid-column-start:87;",
      "grid-column-start:88;",
      "grid-column-start:89;",
      "grid-column-start:90;",
      "grid-column-start:91;",
      "grid-column-start:92;",
      "grid-column-start:93;",
      "grid-column-start:94;",
      "grid-column-start:95;",
      "grid-column-start:96;",
      "grid-column-start:97;",
      "grid-column-start:98;",
      "grid-column-start:99;",
      "grid-column-start:100;",
      "grid-column-end:1;",
      "grid-column-end:2;",
      "grid-column-end:3;",
      "grid-column-end:4;",
      "grid-column-end:5;",
      "grid-column-end:6;",
      "grid-column-end:7;",
      "grid-column-end:8;",
      "grid-column-end:9;",
      "grid-column-end:10;",
      "grid-column-end:11;",
      "grid-column-end:12;",
      "grid-column-end:13;",
      "grid-column-end:14;",
      "grid-column-end:15;",
      "grid-column-end:16;",
      "grid-column-end:17;",
      "grid-column-end:18;",
      "grid-column-end:19;",
      "grid-column-end:20;",
      "grid-column-end:21;",
      "grid-column-end:22;",
      "grid-column-end:23;",
      "grid-column-end:24;",
      "grid-column-end:25;",
      "grid-column-end:26;",
      "grid-column-end:27;",
      "grid-column-end:28;",
      "grid-column-end:29;",
      "grid-column-end:30;",
      "grid-column-end:31;",
      "grid-column-end:32;",
      "grid-column-end:33;",
      "grid-column-end:34;",
      "grid-column-end:35;",
      "grid-column-end:36;",
      "grid-column-end:37;",
      "grid-column-end:38;",
      "grid-column-end:39;",
      "grid-column-end:40;",
      "grid-column-end:41;",
      "grid-column-end:42;",
      "grid-column-end:43;",
      "grid-column-end:44;",
      "grid-column-end:45;",
      "grid-column-end:46;",
      "grid-column-end:47;",
      "grid-column-end:48;",
      "grid-column-end:49;",
      "grid-column-end:50;",
      "grid-column-end:51;",
      "grid-column-end:52;",
      "grid-column-end:53;",
      "grid-column-end:54;",
      "grid-column-end:55;",
      "grid-column-end:56;",
      "grid-column-end:57;",
      "grid-column-end:58;",
      "grid-column-end:59;",
      "grid-column-end:60;",
      "grid-column-end:61;",
      "grid-column-end:62;",
      "grid-column-end:63;",
      "grid-column-end:64;",
      "grid-column-end:65;",
      "grid-column-end:66;",
      "grid-column-end:67;",
      "grid-column-end:68;",
      "grid-column-end:69;",
      "grid-column-end:70;",
      "grid-column-end:71;",
      "grid-column-end:72;",
      "grid-column-end:73;",
      "grid-column-end:74;",
      "grid-column-end:75;",
      "grid-column-end:76;",
      "grid-column-end:77;",
      "grid-column-end:78;",
      "grid-column-end:79;",
      "grid-column-end:80;",
      "grid-column-end:81;",
      "grid-column-end:82;",
      "grid-column-end:83;",
      "grid-column-end:84;",
      "grid-column-end:85;",
      "grid-column-end:86;",
      "grid-column-end:87;",
      "grid-column-end:88;",
      "grid-column-end:89;",
      "grid-column-end:90;",
      "grid-column-end:91;",
      "grid-column-end:92;",
      "grid-column-end:93;",
      "grid-column-end:94;",
      "grid-column-end:95;",
      "grid-column-end:96;",
      "grid-column-end:97;",
      "grid-column-end:98;",
      "grid-column-end:99;",
      "grid-column-end:100;",
      "grid-row-start:1;",
      "grid-row-start:2;",
      "grid-row-start:3;",
      "grid-row-start:4;",
      "grid-row-start:5;",
      "grid-row-start:6;",
      "grid-row-start:7;",
      "grid-row-start:8;",
      "grid-row-start:9;",
      "grid-row-start:10;",
      "grid-row-start:11;",
      "grid-row-start:12;",
      "grid-row-start:13;",
      "grid-row-start:14;",
      "grid-row-start:15;",
      "grid-row-start:16;",
      "grid-row-start:17;",
      "grid-row-start:18;",
      "grid-row-start:19;",
      "grid-row-start:20;",
      "grid-row-start:21;",
      "grid-row-start:22;",
      "grid-row-start:23;",
      "grid-row-start:24;",
      "grid-row-start:25;",
      "grid-row-start:26;",
      "grid-row-start:27;",
      "grid-row-start:28;",
      "grid-row-start:29;",
      "grid-row-start:30;",
      "grid-row-start:31;",
      "grid-row-start:32;",
      "grid-row-start:33;",
      "grid-row-start:34;",
      "grid-row-start:35;",
      "grid-row-start:36;",
      "grid-row-start:37;",
      "grid-row-start:38;",
      "grid-row-start:39;",
      "grid-row-start:40;",
      "grid-row-start:41;",
      "grid-row-start:42;",
      "grid-row-start:43;",
      "grid-row-start:44;",
      "grid-row-start:45;",
      "grid-row-start:46;",
      "grid-row-start:47;",
      "grid-row-start:48;",
      "grid-row-start:49;",
      "grid-row-start:50;",
      "grid-row-start:51;",
      "grid-row-start:52;",
      "grid-row-start:53;",
      "grid-row-start:54;",
      "grid-row-start:55;",
      "grid-row-start:56;",
      "grid-row-start:57;",
      "grid-row-start:58;",
      "grid-row-start:59;",
      "grid-row-start:60;",
      "grid-row-start:61;",
      "grid-row-start:62;",
      "grid-row-start:63;",
      "grid-row-start:64;",
      "grid-row-start:65;",
      "grid-row-start:66;",
      "grid-row-start:67;",
      "grid-row-start:68;",
      "grid-row-start:69;",
      "grid-row-start:70;",
      "grid-row-start:71;",
      "grid-row-start:72;",
      "grid-row-start:73;",
      "grid-row-start:74;",
      "grid-row-start:75;",
      "grid-row-start:76;",
      "grid-row-start:77;",
      "grid-row-start:78;",
      "grid-row-start:79;",
      "grid-row-start:80;",
      "grid-row-start:81;",
      "grid-row-start:82;",
      "grid-row-start:83;",
      "grid-row-start:84;",
      "grid-row-start:85;",
      "grid-row-start:86;",
      "grid-row-start:87;",
      "grid-row-start:88;",
      "grid-row-start:89;",
      "grid-row-start:90;",
      "grid-row-start:91;",
      "grid-row-start:92;",
      "grid-row-start:93;",
      "grid-row-start:94;",
      "grid-row-start:95;",
      "grid-row-start:96;",
      "grid-row-start:97;",
      "grid-row-start:98;",
      "grid-row-start:99;",
      "grid-row-start:100;",
      "grid-row-end:1;",
      "grid-row-end:2;",
      "grid-row-end:3;",
      "grid-row-end:4;",
      "grid-row-end:5;",
      "grid-row-end:6;",
      "grid-row-end:7;",
      "grid-row-end:8;",
      "grid-row-end:9;",
      "grid-row-end:10;",
      "grid-row-end:11;",
      "grid-row-end:12;",
      "grid-row-end:13;",
      "grid-row-end:14;",
      "grid-row-end:15;",
      "grid-row-end:16;",
      "grid-row-end:17;",
      "grid-row-end:18;",
      "grid-row-end:19;",
      "grid-row-end:20;",
      "grid-row-end:21;",
      "grid-row-end:22;",
      "grid-row-end:23;",
      "grid-row-end:24;",
      "grid-row-end:25;",
      "grid-row-end:26;",
      "grid-row-end:27;",
      "grid-row-end:28;",
      "grid-row-end:29;",
      "grid-row-end:30;",
      "grid-row-end:31;",
      "grid-row-end:32;",
      "grid-row-end:33;",
      "grid-row-end:34;",
      "grid-row-end:35;",
      "grid-row-end:36;",
      "grid-row-end:37;",
      "grid-row-end:38;",
      "grid-row-end:39;",
      "grid-row-end:40;",
      "grid-row-end:41;",
      "grid-row-end:42;",
      "grid-row-end:43;",
      "grid-row-end:44;",
      "grid-row-end:45;",
      "grid-row-end:46;",
      "grid-row-end:47;",
      "grid-row-end:48;",
      "grid-row-end:49;",
      "grid-row-end:50;",
      "grid-row-end:51;",
      "grid-row-end:52;",
      "grid-row-end:53;",
      "grid-row-end:54;",
      "grid-row-end:55;",
      "grid-row-end:56;",
      "grid-row-end:57;",
      "grid-row-end:58;",
      "grid-row-end:59;",
      "grid-row-end:60;",
      "grid-row-end:61;",
      "grid-row-end:62;",
      "grid-row-end:63;",
      "grid-row-end:64;",
      "grid-row-end:65;",
      "grid-row-end:66;",
      "grid-row-end:67;",
      "grid-row-end:68;",
      "grid-row-end:69;",
      "grid-row-end:70;",
      "grid-row-end:71;",
      "grid-row-end:72;",
      "grid-row-end:73;",
      "grid-row-end:74;",
      "grid-row-end:75;",
      "grid-row-end:76;",
      "grid-row-end:77;",
      "grid-row-end:78;",
      "grid-row-end:79;",
      "grid-row-end:80;",
      "grid-row-end:81;",
      "grid-row-end:82;",
      "grid-row-end:83;",
      "grid-row-end:84;",
      "grid-row-end:85;",
      "grid-row-end:86;",
      "grid-row-end:87;",
      "grid-row-end:88;",
      "grid-row-end:89;",
      "grid-row-end:90;",
      "grid-row-end:91;",
      "grid-row-end:92;",
      "grid-row-end:93;",
      "grid-row-end:94;",
      "grid-row-end:95;",
      "grid-row-end:96;",
      "grid-row-end:97;",
      "grid-row-end:98;",
      "grid-row-end:99;",
      "grid-row-end:100;",
      "grid-gap:auto;",
      "grid-gap:0rem;",
      "grid-gap:0.0625rem;",
      "grid-gap:0.125rem;",
      "grid-gap:0.25rem;",
      "grid-gap:0.375rem;",
      "grid-gap:0.5rem;",
      "grid-gap:0.75rem;",
      "grid-gap:1rem;",
      "grid-gap:1.5rem;",
      "grid-gap:2rem;",
      "grid-gap:3rem;",
      "grid-gap:10%;",
      "grid-gap:20%;",
      "grid-gap:30%;",
      "grid-gap:40%;",
      "grid-gap:50%;",
      "grid-gap:60%;",
      "grid-gap:70%;",
      "grid-gap:80%;",
      "grid-gap:90%;",
      "grid-gap:100%;",
    ]
  `);
});
