import { BaseProps, InputTypes, KeyofJSX, OrString } from './interfaces';
import styled from 'styled-components';

const intrinsicElements: KeyofJSX[] = [
  'a',
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'b',
  'base',
  'bdi',
  'bdo',
  'big',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'caption',
  'cite',
  'code',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'embed',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'kbd',
  'keygen',
  'label',
  'legend',
  'li',
  'link',
  'main',
  'map',
  'mark',
  'menu',
  'menuitem',
  'meta',
  'meter',
  'nav',
  'noindex',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'output',
  'p',
  'param',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'slot',
  'script',
  'section',
  'select',
  'small',
  'source',
  'span',
  'strong',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'template',
  'tbody',
  'td',
  'textarea',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'u',
  'ul',
  'var',
  'video',
  'wbr',
  'webview',
  'svg',
  'animate',
  'animateMotion',
  'animateTransform',
  'circle',
  'clipPath',
  'defs',
  'desc',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
  'filter',
  'foreignObject',
  'g',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'metadata',
  'mpath',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'stop',
  'switch',
  'symbol',
  'textPath',
  'tspan',
  'use',
  'view',
];

const inputTypes = [
  'checkbox',
  'color',
  'email',
  'file',
  'number',
  'password',
  'radio',
  'range',
  'text',
];

export const isInputType = (key: OrString<InputTypes>): key is InputTypes =>
  inputTypes.includes(key as InputTypes);

export const isintrinsicElement = (key: OrString<KeyofJSX>): key is KeyofJSX =>
  intrinsicElements.includes(key as KeyofJSX);

const handleIntrinsicElements = (props: BaseProps) => {
  const cast = Object.keys(props).reduce(
    (acc, key: string) => {
      return isintrinsicElement(key)
        ? { as: key }
        : isInputType(key)
          ? { as: 'input' as KeyofJSX, type: key }
          : acc;
    },
    { as: undefined, type: undefined },
  );

  return {
    as: cast?.as as any,
    type: cast?.type,
  };
};

export const BaseStyle = styled.div.attrs(handleIntrinsicElements)<BaseProps>`
  box-sizing: border-box;
  margin: 0;
  padding: 0;
`;
