import { attach } from './attachmentHandlers';

export const attachmentsDefault = {
  undefined: () => '',
  css: attach.classes(),
  dark: attach.theme(),
  important: attach.important(),
  xs: attach.media('(min-width: 640px)'),
  sm: attach.media('(min-width: 768px)'),
  md: attach.media('(min-width: 1024px)'),
  lg: attach.media('(min-width: 1440px)'),
  xl: attach.media('(min-width: 1920px)'),
  focus: attach.pseudo(':focus'),
  within: attach.pseudo(':focus-within'),
  after: attach.pseudo(':after'),
  before: attach.pseudo(':before'),
  active: attach.pseudo(':active'),
  checked: attach.pseudo(':checked'),
  disabled: attach.pseudo(':disabled'),
  hover: attach.pseudo(':hover'),
  visited: attach.pseudo(':visited'),
  child: attach.pseudo('>*'),
  last: attach.pseudo('>:last-child'),
  first: attach.pseudo('>:first-child'),
  adjacent: attach.pseudo('~*'),
  sibling: attach.pseudo('+*'),
  odd: attach.pseudo(':nth-child(odd)'),
  even: attach.pseudo(':nth-child(even)'),
  kf: attach.keyframe({
    from: '0%',
    quarter: '25%',
    third: '33%',
    half: '50%',
    x2third: '66%',
    x3quarter: '75%',
    to: '100%',
  }),
};
