export const pseudoElements = [
  ['focus', ':focus:focus-within'],
  ['after', ':after'],
  ['before', ':before'],
  ['active', ':active'],
  ['checked', ':checked'],
  ['disabled', ':disabled'],
  ['hover', ':hover'],
  ['visited', ':visited'],
  ['child', '>*'],
  ['last', ':last-child'],
  ['first', ':first-child'],
  ['sibling', '+*'],
  ['odd', ':nth-child(odd)'],
  ['even', ':nth-child(even)'],
] as const;
export type PseudoElements = typeof pseudoElements[number][0];

export const mediaQueries = [
  ['xs', '(min-width: 640px)'],
  ['sm', '(min-width: 768px)'],
  ['md', '(min-width: 1024px)'],
  ['lg', '(min-width: 1440px)'],
  ['xl', '(min-width: 1920px)'],
] as const;
export type MediaQueries = typeof mediaQueries[number][0];

export const sd_1 = [
  ['0 1px 1px', '0', 'rgba(0,0,0,0.14)'],
  ['0 2px 1px', '-1px', 'rgba(0,0,0,0.12)'],
  ['0 1px 3px', '0', 'rgba(0,0,0,0.20)'],
];
export const sd_2 = [
  ['0 2px 2px', '0', 'rgba(0,0,0,0.14)'],
  ['0 3px 1px', '-2px', 'rgba(0,0,0,0.12)'],
  ['0 1px 5px', '0', 'rgba(0,0,0,0.20)'],
];
export const sd_3 = [
  ['0 3px 4px', '0', 'rgba(0,0,0,0.14)'],
  ['0 3px 3px', '-2px', 'rgba(0,0,0,0.12)'],
  ['0 1px 8px', '0', 'rgba(0,0,0,0.20)'],
];
export const sd_4 = [
  ['0 4px 5px 0', '0', 'rgba(0,0,0,0.14)'],
  ['0 1px 10px', '0', 'rgba(0,0,0,0.12)'],
  ['0 2px 4px', '-1px', 'rgba(0,0,0,0.20)'],
];
export const sd_6 = [
  ['0 6px 10px', '0', 'rgba(0,0,0,0.14)'],
  ['0 1px 18px', '0', 'rgba(0,0,0,0.12)'],
  ['0 3px 5px', '-1px', 'rgba(0,0,0,0.20)'],
];
export const sd_8 = [
  ['0 8px 10px', ' 1px', 'rgba(0,0,0,0.14)'],
  ['0 3px 14px', ' 2px', 'rgba(0,0,0,0.12)'],
  ['0 5px 5px', '-3px', 'rgba(0,0,0,0.20)'],
];
export const sd_9 = [
  ['0 9px 12px', '1px', 'rgba(0,0,0,0.14)'],
  ['0 3px 16px', '2px', 'rgba(0,0,0,0.12)'],
  ['0 5px 6px', '-3px', 'rgba(0,0,0,0.20)'],
];
export const sd_12 = [
  ['0 12px 17px', '2px', 'rgba(0,0,0,0.14)'],
  ['0 5px 22px', '4px', 'rgba(0,0,0,0.12)'],
  ['0 7px 8px', '-4px', 'rgba(0,0,0,0.20)'],
];
export const sd_16 = [
  ['0 16px 24px', '2px', 'rgba(0,0,0,0.14)'],
  ['0 6px 30px', '5px', 'rgba(0,0,0,0.12)'],
  ['0 8px 10px', '-5px', 'rgba(0,0,0,0.20)'],
];
export const sd_24 = [
  ['0 24px 38px', '3px', 'rgba(0,0,0,0.14)'],
  ['0 9px 46px', '8px', 'rgba(0,0,0,0.12)'],
  ['0 11px 15px', '-7px', 'rgba(0,0,0,0.20)'],
];

export const textTags = [
  'a',
  'b',
  'caption',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'li',
  'p',
  'label',
  'span',
  'strong',
  'td',
  'th',
] as const;

export const svgTags = [
  'animate',
  'circle',
  'clipPath',
  'defs',
  'desc',
  'ellipse',
  'feBlend',
  'feColorMatrix',
  'feComponentTransfer',
  'feComposite',
  'feConvolveMatrix',
  'feDiffuseLighting',
  'feDisplacementMap',
  'feDistantLight',
  'feDropShadow',
  'feFlood',
  'feFuncA',
  'feFuncB',
  'feFuncG',
  'feFuncR',
  'feGaussianBlur',
  'feImage',
  'feMerge',
  'feMergeNode',
  'feMorphology',
  'feOffset',
  'fePointLight',
  'feSpecularLighting',
  'feSpotLight',
  'feTile',
  'feTurbulence',
  'filter',
  'foreignObject',
  'g',
  'image',
  'line',
  'linearGradient',
  'marker',
  'mask',
  'metadata',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'radialGradient',
  'rect',
  'stop',
  'svg',
  'switch',
  'symbol',
  'text',
  'textPath',
  'tspan',
  'use',
  'view',
] as const;

export const viewTags = [
  ...svgTags,
  'abbr',
  'address',
  'area',
  'article',
  'aside',
  'audio',
  'base',
  'bdi',
  'bdo',
  'big',
  'blockquote',
  'body',
  'br',
  'button',
  'canvas',
  'cite',
  'code',
  'col',
  'colgroup',
  'data',
  'datalist',
  'dd',
  'del',
  'details',
  'dfn',
  'dialog',
  'div',
  'dl',
  'dt',
  'em',
  'embed',
  'fieldset',
  'figcaption',
  'figure',
  'footer',
  'form',
  'head',
  'header',
  'hgroup',
  'hr',
  'html',
  'i',
  'iframe',
  'img',
  'input',
  'ins',
  'kbd',
  'keygen',
  'legend',
  'link',
  'main',
  'map',
  'mark',
  'menu',
  'menuitem',
  'meta',
  'meter',
  'nav',
  'noscript',
  'object',
  'ol',
  'optgroup',
  'option',
  'output',
  'param',
  'picture',
  'pre',
  'progress',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'slot',
  'script',
  'section',
  'select',
  'small',
  'source',
  'style',
  'sub',
  'summary',
  'sup',
  'table',
  'template',
  'tbody',
  'textarea',
  'tfoot',
  'thead',
  'time',
  'title',
  'tr',
  'track',
  'u',
  'ul',
  'var',
  'video',
  'wbr',
  'webview',
] as const;
