import { KeyinTypeOrString } from '../../helpers/interfaces';
type Options =
  | 'tl_full'
  | 'tl_half'
  | 'tl_full_neg'
  | 'tl_half_neg'
  | 'tlx_full'
  | 'tlx_half'
  | 'tlx_full_neg'
  | 'tlx_half_neg'
  | 'tly_full'
  | 'tly_half'
  | 'tly_full_neg'
  | 'tly_half_neg'
  | 'ori_center'
  | 'ori_top'
  | 'ori_top_right'
  | 'ori_right'
  | 'ori_bottom_right'
  | 'ori_bottom'
  | 'ori_bottom_left'
  | 'ori_left'
  | 'ori_top_left'
  | 'sk_NUMBER'
  | 'skx_NUMBER'
  | 'sky_NUMBER'
  | 'sk_neg_NUMBER'
  | 'skx_neg_NUMBER'
  | 'sky_neg_NUMBER'
  | 'sl_NUMBER'
  | 'slx_NUMBER'
  | 'sly_NUMBER'
  | 'sl_neg_NUMBER'
  | 'slx_neg_NUMBER'
  | 'sly_neg_NUMBER'
  | 'rt_NUMBER'
  | 'rt_neg_NUMBER'
  | 'tl_NUMBER'
  | 'tlx_NUMBER'
  | 'tly_NUMBER'
  | 'tl_neg_NUMBER'
  | 'tlx_neg_NUMBER'
  | 'tly_neg_NUMBER';

type Props = KeyinTypeOrString<Options>;

export default Props;
